<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Andrew Leifer: <?php echo $title; ?></title>

    <!-- Framework CSS -->
    <link rel="stylesheet" href="css/blueprint/screen.css" type="text/css" media="screen, projec
tion">
    <link rel="stylesheet" href="css/blueprint/print.css" type="text/css" media="print">

    <!--[if lt IE 8]><link rel="stylesheet" href="css/blueprint/ie.css" type="text/css" media="s
creen, projection"><![endif]-->

    <!-- Import fancy-type plugin for the sample page. -->
    <link rel="stylesheet" href="css/blueprint/plugins/fancy-type/screen.css" type="text/css" me
dia="screen, projection">

    <link rel="stylesheet" href="css/style.css" type="text/css" media="screen, projection">
  </head>
<body>

<hr id="topstripe">
<div class="container">
<h1 id="mast" class="span-8"><a href="/">Andrew Leifer</a></h1>
<div class="span-16 last"><ul class="buttonbar"><li class="span-2"><a href="index.php">Home</a></li><li class="span-2"><a href="research.php">Research</a></li><li class="span-2"><a href="writings.php">Writings</a></li><li class="span-2"><a href="speeches.php">Speeches</a></li>
<li class="span-2"><a href="links.php">Links</a></li>
<li class="span-2"><a href="software.php">Software</a></li><li class="span-2"><a href="cv.php">CV</a></li>
</ul>
</div>
<hr class="space">

